apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-springboot
  template:
    metadata:
      labels:
        app: test-springboot
    spec:
      containers:
        - name: springboot
          image: nadeem9975/php:v1
          ports:
            - containerPort: 8000
          env:
            - name: PORT
              value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: test-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: test-springboot
